import { describe, it, expect } from "vitest";
import { checkAIActCompliance } from "@/lib/analysis/ai-act-checker";

const aiGeneratedText = `
This content was generated by AI using GPT-4. The AI system was trained on
publicly available datasets. This AI-generated report is intended for informational
purposes only. It may contain errors and should be verified by a human reviewer.
Human oversight was applied during the review process.
`;

const highRiskText = `
Our AI-powered hiring decision system automatically screens job candidates based on
their CV and interview performance. The system uses biometric facial recognition
during video interviews to assess candidate suitability for employment.
`;

const unacceptableRiskText = `
Our social credit scoring system monitors citizen behavior and assigns behavioral
scoring of citizens based on their social media activity and purchasing patterns.
The system uses real-time biometric identification in public spaces for mass surveillance.
`;

const neutralText = `
The weather forecast for tomorrow indicates partly cloudy skies with temperatures
around 22 degrees Celsius. Wind speeds will be moderate from the northwest.
Local authorities recommend bringing an umbrella just in case.
`;

describe("EU AI Act Compliance Checker", () => {
  describe("checkAIActCompliance", () => {
    it("should pass transparency checks for properly labeled AI content", () => {
      const result = checkAIActCompliance(aiGeneratedText);
      expect(result.overallScore).toBeGreaterThan(50);
      expect(["compliant", "mostly_compliant"]).toContain(result.complianceLevel);
      const aiDisclosure = result.checks.find(c => c.id === "art50_ai_disclosure");
      expect(aiDisclosure?.status).toBe("pass");
    });

    it("should flag high-risk AI domains", () => {
      const result = checkAIActCompliance(highRiskText);
      expect(result.riskLevel).toBe("high");
      const domainCheck = result.checks.find(c => c.id === "annex3_domain");
      expect(domainCheck).toBeTruthy();
      expect(domainCheck?.status).toBe("warning");
    });

    it("should flag unacceptable risk practices", () => {
      const result = checkAIActCompliance(unacceptableRiskText);
      expect(result.riskLevel).toBe("unacceptable");
      const prohibitedCheck = result.checks.find(c => c.id === "art5_prohibited");
      expect(prohibitedCheck).toBeTruthy();
      expect(prohibitedCheck?.status).toBe("fail");
      expect(prohibitedCheck?.severity).toBe("critical");
    });

    it("should classify neutral content as minimal risk", () => {
      const result = checkAIActCompliance(neutralText);
      expect(result.riskLevel).toBe("minimal");
      expect(result.overallScore).toBeGreaterThanOrEqual(70);
    });

    it("should return correct interface shape", () => {
      const result = checkAIActCompliance(aiGeneratedText);
      expect(result).toHaveProperty("overallScore");
      expect(result).toHaveProperty("complianceLevel");
      expect(result).toHaveProperty("checks");
      expect(result).toHaveProperty("riskLevel");
      expect(result).toHaveProperty("summary");
      expect(Array.isArray(result.checks)).toBe(true);
    });

    it("should have properly structured checks", () => {
      const result = checkAIActCompliance(highRiskText);
      for (const check of result.checks) {
        expect(check).toHaveProperty("id");
        expect(check).toHaveProperty("article");
        expect(check).toHaveProperty("requirement");
        expect(check).toHaveProperty("status");
        expect(check).toHaveProperty("detail");
        expect(check).toHaveProperty("severity");
        expect(["pass", "fail", "warning", "not_applicable"]).toContain(check.status);
        expect(["critical", "major", "minor", "info"]).toContain(check.severity);
      }
    });

    it("should detect missing human oversight in high-risk content", () => {
      const noOversightText = `
        Our AI system for hiring decision and employment screening automatically
        processes job candidates using biometric data. The system operates fully
        autonomously without any manual intervention.
      `;
      const result = checkAIActCompliance(noOversightText);
      const oversightCheck = result.checks.find(c => c.id === "art14_oversight");
      expect(oversightCheck?.status).toBe("fail");
    });

    it("should have overall score between 0 and 100", () => {
      const result = checkAIActCompliance(aiGeneratedText);
      expect(result.overallScore).toBeGreaterThanOrEqual(0);
      expect(result.overallScore).toBeLessThanOrEqual(100);
    });

    it("should produce non-empty summary", () => {
      const result = checkAIActCompliance(neutralText);
      expect(result.summary.length).toBeGreaterThan(0);
    });

    it("should have valid compliance levels", () => {
      const result = checkAIActCompliance(aiGeneratedText);
      expect(["compliant", "mostly_compliant", "partially_compliant", "non_compliant"]).toContain(result.complianceLevel);
    });

    it("should have valid risk levels", () => {
      const result = checkAIActCompliance(neutralText);
      expect(["unacceptable", "high", "limited", "minimal"]).toContain(result.riskLevel);
    });
  });
});
