/**
 * EU AI Act Compliance Checker
 *
 * Deterministic checklist based on the EU AI Act (Regulation 2024/1689).
 * Checks content against Art. 50 transparency obligations and Art. 6 risk classification.
 *
 * References:
 * - EU AI Act Art. 50: Transparency obligations for certain AI systems
 * - EU AI Act Art. 6, Annex III: High-risk AI system classification
 * - EU AI Act Art. 52: Transparency for specific AI systems (deepfakes, chatbots)
 * - EU AI Act Recitals 132-135: Transparency guidance
 *
 * All checks are regex/heuristic-based — no LLM calls.
 * Updated April 2026.
 */

export interface AIActCheck {
  id: string;
  article: string;
  requirement: string;
  status: "pass" | "fail" | "warning" | "not_applicable";
  detail: string;
  severity: "critical" | "major" | "minor" | "info";
}

export interface AIActResult {
  overallScore: number; // 0 = non-compliant, 100 = fully compliant
  complianceLevel: "compliant" | "mostly_compliant" | "partially_compliant" | "non_compliant";
  checks: AIActCheck[];
  riskLevel: "unacceptable" | "high" | "limited" | "minimal";
  summary: string;
}

// High-risk domain keywords from Annex III of the EU AI Act
const HIGH_RISK_DOMAINS = {
  biometric: /\b(biometric|facial recognition|fingerprint|iris scan|voice identification|face detection)\b/gi,
  critical_infrastructure: /\b(power grid|water supply|traffic management|critical infrastructure|energy system|transport network)\b/gi,
  education: /\b(educational scoring|student assessment|exam grading|admission decision|academic evaluation)\b/gi,
  employment: /\b(hiring decision|recruitment|cv screening|employment|job candidate|worker evaluation|performance scoring)\b/gi,
  essential_services: /\b(credit scoring|credit decision|insurance pricing|social benefit|welfare eligibility|loan approval)\b/gi,
  law_enforcement: /\b(crime prediction|recidivism|law enforcement|criminal profiling|surveillance|policing)\b/gi,
  migration: /\b(asylum|border control|migration|visa decision|immigration|refugee)\b/gi,
  justice: /\b(judicial decision|sentencing|court|legal ruling|parole decision)\b/gi,
};

// Unacceptable risk indicators from Art. 5
const UNACCEPTABLE_RISK = {
  social_scoring: /\b(social credit|citizen score|behavioral scoring of citizens|social ranking system)\b/gi,
  subliminal: /\b(subliminal manipulation|unconscious influence|covert persuasion technique)\b/gi,
  vulnerability_exploitation: /\b(exploit.{0,30}(?:children|elderly|disabled|vulnerable)|target.{0,30}(?:mental health|addiction|cognitive limitation))\b/gi,
  real_time_biometric: /\b(real[- ]?time.{0,20}biometric|live facial recognition.{0,20}public space|mass surveillance)\b/gi,
};

// Art. 50 transparency disclosure patterns
const TRANSPARENCY_DISCLOSURES = {
  ai_disclosure: /\b(generated by (?:AI|artificial intelligence)|AI[- ]generated|machine[- ]generated|produced by (?:an? )?(?:AI|language model|neural network))\b/gi,
  model_name: /\b(GPT|Claude|Gemini|LLaMA|Mistral|OpenAI|Anthropic|Google AI|Meta AI|Microsoft Copilot)\b/gi,
  purpose_statement: /\b(this (?:content|text|article|report) (?:is|was) (?:created|generated|produced|written) (?:to|for|in order to))\b/gi,
  training_data_disclosure: /\b(trained on|training data|data sources include|model trained|fine[- ]?tuned on|learning from)\b/gi,
  human_oversight: /\b(human review|human oversight|reviewed by|verified by|edited by|human in the loop|human supervision)\b/gi,
  limitation_disclosure: /\b(limitation|may contain errors|not guaranteed|AI hallucination|factual accuracy not guaranteed|should be verified)\b/gi,
  deepfake_label: /\b(deepfake|synthetically generated|AI[- ]generated (?:image|video|audio)|artificially created)\b/gi,
};

/**
 * Classify the risk level of content based on its domain.
 * Art. 6 + Annex III of the EU AI Act.
 */
function classifyRisk(text: string): { level: AIActResult["riskLevel"]; domains: string[] } {
  // Check unacceptable risk first
  for (const [category, pattern] of Object.entries(UNACCEPTABLE_RISK)) {
    if (pattern.test(text)) {
      pattern.lastIndex = 0;
      return { level: "unacceptable", domains: [category] };
    }
    pattern.lastIndex = 0;
  }

  // Check high-risk domains
  const highRiskDomains: string[] = [];
  for (const [domain, pattern] of Object.entries(HIGH_RISK_DOMAINS)) {
    if (pattern.test(text)) {
      highRiskDomains.push(domain);
    }
    pattern.lastIndex = 0;
  }

  if (highRiskDomains.length > 0) return { level: "high", domains: highRiskDomains };

  // Check for chatbot/AI interaction indicators (limited risk under Art. 50)
  const isAIContent = TRANSPARENCY_DISCLOSURES.ai_disclosure.test(text) || TRANSPARENCY_DISCLOSURES.model_name.test(text);
  TRANSPARENCY_DISCLOSURES.ai_disclosure.lastIndex = 0;
  TRANSPARENCY_DISCLOSURES.model_name.lastIndex = 0;

  if (isAIContent) return { level: "limited", domains: ["ai_generated_content"] };

  return { level: "minimal", domains: [] };
}

/**
 * Run EU AI Act compliance checks on content.
 * All checks are deterministic (regex/heuristic).
 */
export function checkAIActCompliance(text: string, url?: string): AIActResult {
  const checks: AIActCheck[] = [];
  const wordCount = text.split(/\s+/).length;

  // 1. Risk classification
  const risk = classifyRisk(text);

  if (risk.level === "unacceptable") {
    checks.push({
      id: "art5_prohibited",
      article: "Art. 5",
      requirement: "Content must not involve prohibited AI practices",
      status: "fail",
      detail: `Content appears to involve prohibited AI practice: ${risk.domains.join(", ")}. The EU AI Act prohibits these uses.`,
      severity: "critical",
    });
  }

  // 2. Art. 50(1) — AI system disclosure
  const hasAIDisclosure = TRANSPARENCY_DISCLOSURES.ai_disclosure.test(text);
  TRANSPARENCY_DISCLOSURES.ai_disclosure.lastIndex = 0;
  const hasModelName = TRANSPARENCY_DISCLOSURES.model_name.test(text);
  TRANSPARENCY_DISCLOSURES.model_name.lastIndex = 0;
  const looksAIGenerated = hasModelName || /\b(generated|produced|created)\b.*\b(AI|model|system)\b/i.test(text);

  if (looksAIGenerated) {
    checks.push({
      id: "art50_ai_disclosure",
      article: "Art. 50(1)",
      requirement: "AI-generated content must be clearly labeled as such",
      status: hasAIDisclosure ? "pass" : "fail",
      detail: hasAIDisclosure
        ? "Content includes AI generation disclosure."
        : "Content appears AI-related but lacks explicit AI generation disclosure.",
      severity: "major",
    });
  }

  // 3. Art. 50(2) — Deepfake labeling
  const hasDeepfakeContent = TRANSPARENCY_DISCLOSURES.deepfake_label.test(text);
  TRANSPARENCY_DISCLOSURES.deepfake_label.lastIndex = 0;
  const mentionsImageVideo = /\b(image|video|audio|photo|picture|recording)\b/gi.test(text);

  if (hasDeepfakeContent) {
    checks.push({
      id: "art50_deepfake",
      article: "Art. 50(2)",
      requirement: "Synthetic media (deepfakes) must be labeled as artificially generated",
      status: hasDeepfakeContent ? "warning" : "pass",
      detail: "Content references synthetic/AI-generated media. Ensure proper labeling is applied.",
      severity: "major",
    });
  }

  // 4. Purpose declaration (transparency best practice)
  const hasPurpose = TRANSPARENCY_DISCLOSURES.purpose_statement.test(text);
  TRANSPARENCY_DISCLOSURES.purpose_statement.lastIndex = 0;

  if (looksAIGenerated) {
    checks.push({
      id: "art50_purpose",
      article: "Art. 50(1)",
      requirement: "Purpose of AI-generated content should be disclosed",
      status: hasPurpose ? "pass" : "warning",
      detail: hasPurpose
        ? "Content includes purpose declaration."
        : "Consider adding a purpose statement for AI-generated content.",
      severity: "minor",
    });
  }

  // 5. Training data transparency
  const hasTrainingDisclosure = TRANSPARENCY_DISCLOSURES.training_data_disclosure.test(text);
  TRANSPARENCY_DISCLOSURES.training_data_disclosure.lastIndex = 0;

  if (risk.level === "high" || risk.level === "limited") {
    checks.push({
      id: "art50_training",
      article: "Art. 50(1)(c)",
      requirement: "Training data sources should be disclosed for high/limited-risk AI content",
      status: hasTrainingDisclosure ? "pass" : "warning",
      detail: hasTrainingDisclosure
        ? "Training data sources are referenced."
        : "No training data disclosure found. Art. 50 recommends transparency about data sources.",
      severity: risk.level === "high" ? "major" : "minor",
    });
  }

  // 6. Human oversight indication
  const hasHumanOversight = TRANSPARENCY_DISCLOSURES.human_oversight.test(text);
  TRANSPARENCY_DISCLOSURES.human_oversight.lastIndex = 0;

  if (risk.level === "high") {
    checks.push({
      id: "art14_oversight",
      article: "Art. 14",
      requirement: "High-risk AI systems require human oversight measures",
      status: hasHumanOversight ? "pass" : "fail",
      detail: hasHumanOversight
        ? "Human oversight is indicated."
        : "High-risk AI content detected without human oversight indication.",
      severity: "critical",
    });
  }

  // 7. Limitation disclosure
  const hasLimitations = TRANSPARENCY_DISCLOSURES.limitation_disclosure.test(text);
  TRANSPARENCY_DISCLOSURES.limitation_disclosure.lastIndex = 0;

  if (looksAIGenerated && wordCount > 100) {
    checks.push({
      id: "art50_limitations",
      article: "Art. 50(1)",
      requirement: "AI system limitations should be disclosed",
      status: hasLimitations ? "pass" : "warning",
      detail: hasLimitations
        ? "Content acknowledges AI limitations."
        : "No AI limitation disclosure found. Best practice is to disclose potential inaccuracies.",
      severity: "minor",
    });
  }

  // 8. High-risk domain-specific checks
  if (risk.level === "high") {
    checks.push({
      id: "annex3_domain",
      article: "Art. 6 / Annex III",
      requirement: "High-risk AI domain identified — additional obligations apply",
      status: "warning",
      detail: `Content involves high-risk domain(s): ${risk.domains.join(", ")}. Under Art. 6, these require conformity assessment, registration, and ongoing monitoring.`,
      severity: "major",
    });
  }

  // Score calculation
  const criticalFails = checks.filter(c => c.status === "fail" && c.severity === "critical").length;
  const majorFails = checks.filter(c => c.status === "fail" && c.severity === "major").length;
  const warnings = checks.filter(c => c.status === "warning").length;
  const passes = checks.filter(c => c.status === "pass").length;
  const total = checks.length;

  let overallScore: number;
  if (total === 0) {
    overallScore = 80; // No specific AI content detected — general compliance
  } else {
    const deductions = criticalFails * 30 + majorFails * 15 + warnings * 5;
    overallScore = Math.max(0, Math.min(100, 100 - deductions));
  }

  const complianceLevel: AIActResult["complianceLevel"] =
    overallScore >= 80 ? "compliant" :
    overallScore >= 60 ? "mostly_compliant" :
    overallScore >= 35 ? "partially_compliant" : "non_compliant";

  const summary = total === 0
    ? `No specific EU AI Act obligations triggered. Content classified as ${risk.level} risk.`
    : `EU AI Act: ${passes}/${total} checks passed, ${criticalFails} critical issues, ${majorFails} major issues, ${warnings} warnings. Risk level: ${risk.level}.`;

  return {
    overallScore,
    complianceLevel,
    checks,
    riskLevel: risk.level,
    summary,
  };
}
